In [1]:
# https://limitsinx.tistory.com/28 참고
import numpy as np
np.random.seed(0)
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# tensorflow tutorial 1 - tf.Sesson(), sess.run()
hello = tf.constant("Hello, tensorflow")
sess = tf.Session()
print(sess.run(hello))

b'Hello, tensorflow'


In [3]:
# tensorflow tutorial 2 - tf.constant(), tf.add()
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0)
node3 = tf.add(node1, node2)

In [4]:
sess = tf.Session()
print(sess.run([node1, node2]))
print(sess.run(node3))

[3.0, 4.0]
7.0


In [5]:
# tensorflow tutorial 3 - tf.placeholder(), sess.run(모델, 매개변수)
a = tf.placeholder(tf.float32) 
b = tf.placeholder(tf.float32)
adder_node = a + b

In [6]:
sess = tf.Session()
print(sess.run(adder_node, feed_dict={a:3, b:4}))
# 형식을 지정하지 않았기 때문에 Integer와 Array 동시 수용 가능
print(sess.run(adder_node, feed_dict={a:[3,4], b:[4,1]}))

7.0
[7. 5.]


In [3]:
# tensorflow tutorial 4 - linear regression

# 학습데이터
x_train = [1,2,3]
y_train = [1,2,3]

# 추정할 기울기와 절편
W = tf.Variable(tf.random_normal([1]), name='weight') # 1칸짜리 변수를 랜덤으로 추가, 변수의 이름은 weight로 설정
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x_train * W + b
cost = tf.reduce_mean(tf.square(hypothesis - y_train)) # 편차 제곱?
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    sess.run(train) # 학습시작
    if step%100 == 0:
        print(step, sess.run(cost), sess.run(W), sess.run(b))

0 6.4458833 [-0.05461195] [-0.2791675]
100 0.002124303 [0.94646144] [0.12168481]
200 0.0013126897 [0.95791984] [0.09565799]
300 0.00081116316 [0.9669212] [0.07519585]
400 0.0005012496 [0.97399706] [0.05911082]
500 0.00030974174 [0.97955924] [0.04646655]
600 0.00019140072 [0.9839318] [0.03652684]
700 0.00011827352 [0.987369] [0.02871334]
800 7.3087576e-05 [0.9900707] [0.02257147]
900 4.5162626e-05 [0.99219483] [0.01774309]
1000 2.790796e-05 [0.9938644] [0.01394768]
1100 1.7244705e-05 [0.9951769] [0.01096408]
1200 1.0656483e-05 [0.9962086] [0.00861877]
1300 6.5848308e-06 [0.9970196] [0.00677508]
1400 4.0690993e-06 [0.9976571] [0.0053259]
1500 2.5144855e-06 [0.9981583] [0.00418668]
1600 1.5539005e-06 [0.99855226] [0.00329116]
1700 9.602094e-07 [0.99886185] [0.00258719]
1800 5.9344137e-07 [0.9991052] [0.00203387]
1900 3.6680845e-07 [0.9992966] [0.001599]
2000 2.2671189e-07 [0.9994469] [0.00125715]


In [4]:
# tensorflow tutorial 5 - multi linear regression

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# for training examples use tf.placeholder
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [5]:
# trainable variables -> tf.random_normal
w1 = tf.Variable(tf.random_normal([1]), name ='weight1')
w2 = tf.Variable(tf.random_normal([1]), name ='weight2')
w3 = tf.Variable(tf.random_normal([1]), name ='weight3')
b = tf.Variable(tf.random_normal([1]), name ='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # tf.placeholder로 처리된 부분의 값 초기화

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
    feed_dict = {x1 : x1_data, x2 : x2_data, x3 : x3_data, Y : y_data})
    if step%1000 == 0 :
        print(step, "Cost : ",cost_val,"\nPrediction:\n",hy_val, 
        "\nWeight,bias :\n",sess.run(w1),sess.run(w2),sess.run(w3),sess.run(b))

0 Cost :  121688.67 
Prediction:
 [-160.8642  -185.67337 -186.94498 -201.56116 -141.64966] 
Weight,bias :
 [-0.03807741] [-0.75020957] [0.52566046] [-1.2601628]
1000 Cost :  2.4898064 
Prediction:
 [149.08809 186.05853 179.75372 197.65515 141.77834] 
Weight,bias :
 [0.6867333] [0.0726983] [1.2585306] [-1.2487322]
2000 Cost :  2.0783129 
Prediction:
 [149.42252 185.83504 179.86351 197.67758 141.53316] 
Weight,bias :
 [0.6649865] [0.12479357] [1.2285522] [-1.2461096]


# 데이터 입력시 n차 배열을 이용하려면? 이용한다면?

 x=tf.placeholder(tf.float32, shape=[None,3]) 의 의미를 알아야 한다.
 위의 예시 같은 경우 각 변수들을 따로 적어주었기 때문에 shape를 표시할 필요가 없었지만, 만약 x= [[73., 80., 75.], [93.,88.,93.], ...] y = [152., 185., ...] 의 형태로 표현할거라면 x_data가 어떤 matrix형태인지 지정해주는 것이 필요하다.
 
 shape = [None, 3]이란 행은 상관없고, 열이 3개임을 의미한다. 
 즉, x_data 3개를 [a,b,c]로 표현한다는 뜻이다.
 
 x_data를 위와같은 형태로 바꿔주면 tf.Variable(tf.random_normal([3,1]), name='weight') 도 바꿔줘야 한다.
 
 *cf. tf.Variable()은 학습시킬 변수에 사용하고, tf.placeholder()는 학습에 사용할 데이터를 표현할 때 사용한다.*

In [24]:
# tensorflow tutorial 6 - multi linear regression different ver.

x_data = [[1,1], [2,3], [4,5], [6,7], [8,8]]
y_data = [[6], [7], [8], [9], [10]]

x = tf.placeholder(tf.float32, shape =[None,2])
y = tf.placeholder(tf.float32, shape =[None,1])
w = tf.Variable(tf.random_normal([2,1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(x,w)+b
cost = tf.reduce_mean(tf.square(hypothesis - y))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.001).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _, W_val, b_val =sess.run([cost, hypothesis, train, w, b], 
                                               feed_dict={x:x_data, y:y_data})
    if step % 500 == 0:
        print( "\n\n",step, cost_val, hy_val,"\nW_Val:", W_val,"\nb_val:", b_val)



 0 101.9589 [[-0.20985697]
 [-1.1469597 ]
 [-1.9385301 ]
 [-2.7301006 ]
 [-2.9803534 ]] 
W_Val: [[ 0.24012478]
 [-0.4347987 ]] 
b_val: [0.20553057]


 500 3.9403126 [[ 2.6883283]
 [ 4.5902348]
 [ 7.0587   ]
 [ 9.527166 ]
 [11.327959 ]] 
W_Val: [[0.5658036 ]
 [0.66804665]] 
b_val: [1.4560184]


 1000 2.279087 [[ 3.3621557]
 [ 5.246849 ]
 [ 7.3844953]
 [ 9.5221405]
 [10.843918 ]] 
W_Val: [[0.25244182]
 [0.81609744]] 
b_val: [2.2947888]


 1500 1.3577532 [[ 3.8766491]
 [ 5.724984 ]
 [ 7.6169977]
 [ 9.509011 ]
 [10.498696 ]] 
W_Val: [[0.04334305]
 [0.90245265]] 
b_val: [2.9317517]


 2000 0.8396627 [[ 4.2724013]
 [ 6.0724254]
 [ 7.781596 ]
 [ 9.490767 ]
 [10.2544985]] 
W_Val: [[-0.09106346]
 [ 0.94549143]] 
b_val: [3.4186673]
